packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"
catalog:
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@eslint/compat": ^1.2.6
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.20.0
  "@types/node": ^22.13.4
  "@tanstack/react-query": ^5.66.6
  "@tanstack/react-query-devtools": ^5.66.6
  "@popperjs/core": ^2.11.8
  "@tanstack/eslint-plugin-query": ^5.66.1
  "@types/html-minifier-terser": ^7.0.2
  "@types/loadable__component": ^5.13.9
  "@types/lodash": ^4.17.15
  "@types/react": ^18.3.18
  "@types/react-dom": ^18.3.5
  "@types/react-router-dom": ^5.3.3
  "@types/react-syntax-highlighter": ^15.5.13
  "@typescript-eslint/eslint-plugin": ^8.24.1
  "@typescript-eslint/parser": ^8.24.1
  "@vitejs/plugin-react": ^4.3.4
  autoprefixer: ^10.4.20
  postcss: ^8.5.2
  postcss-import: ^16.1.0
  postcss-nesting: ^12.1.5
  tailwindcss: ^3.4.17
  vite: ^5.4.14
  vitest: ^2.1.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  embla-carousel-react: ^8.5.2
  esno: ^4.8.0
  events: ^3.3.0
  formik: ^2.4.6
  framer-motion: ^11.18.2
  i18next: ^23.16.8
  i18next-http-backend: ^2.7.3
  lodash: ^4.17.21
  ofetch: ^1.4.1
  react: ^18.3.1
  react-apexcharts: ^1.7.0
  react-dom: ^18.3.1
  react-error-boundary: ^4.1.2
  react-helmet-async: ^2.0.5
  react-hook-form: ^7.54.2
  react-i18next: ^15.4.1
  react-router-dom: ^6.29.0
  yup: ^1.6.1
  eslint: ^9.20.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-react: ^7.37.4
  globals: ^15.15.0
  husky: ^9.1.7
  lint-staged: ^15.4.3
  prettier: ^3.5.1
  rimraf: ^6.0.1
  turbo: ^2.4.2
  typescript: ^5.7.3
